apiVersion: v1
kind: Pod
metadata:
  name: init-tester
  labels:
    name: init-tester
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
  - name: failed
    image: busybox
    command: [/bin/false]
