apiVersion: v1
kind: Pod
metadata:
  labels:
    run: stress
  name: stressmeout
spec:
  containers:
  - image: vish/stress
    name: stressmeout
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "500Mi"
    args:
      - -cpus
      - "2"
      - -mem-total
      - "1950Mi"
      - -mem-alloc-size
      - "100Mi"
      - -mem-alloc-sleep
      - "1s"
  dnsPolicy: ClusterFirst
  restartPolicy: Always