apiVersion: v1
kind: Pod
metadata:
  name: secondapp
  labels:
    example: second
spec:
  containers:
  - name: webserver
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: busy
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "3600"
    
