apiVersion: v1
kind: Pod
metadata:
  name: basicpod
  labels:
    name: basicpod
spec:
  containers:
  - name: webcont
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: fdlogger
    image: fluent/fluentd
