apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: nileshgule/simpleapp
        readinessProbe:
          periodSeconds: 5
          exec:
            command:
            - ls
        env:
        - name: ilike
          valueFrom:
            configMapKeyRef:
              name: colors
              key: favourite
        envFrom:
        - configMapRef:
            name: colors
